export {
  CPP_CONFIG,
  CSHARP_CONFIG,
  EXTENSION_TO_LANGUAGE,
  JAVA_CONFIG,
  LANGUAGE_REGISTRY,
  LUA_CONFIG,
  PYTHON_CONFIG,
  TYPESCRIPT_CONFIG,
  detectTestFramework,
  getLanguageConfig,
  getLanguageName,
  getSupportedExtensions,
  isLanguageSupported,
  isTestFile,
} from '@autocode/core/graph/language-registry';
