/**
 * @autocode/core - Headless agent core
 *
 * Shared across the desktop Electron app, the VS Code extension, and
 * future UIs (web, JetBrains, CLI). Owns the AI agent layer, auth,
 * worktree management, and security primitives.
 *
 * This package is work-in-progress. Code is being extracted from
 * apps/desktop/src/main/ in stages. See the project's extract-core
 * branch for the migration plan.
 */

export const CORE_PACKAGE_VERSION = '0.0.0';

// Provider types - phase 2 leaf node.
export {
  SupportedProvider,
  type ProviderConfig,
  type ModelResolution,
  type ProviderCapabilities,
} from './providers/types.js';

export {
  ANTHROPIC_CLAUDE_CODE_BETA_HEADER,
  DEFAULT_DEEPSEEK_BASE_URL,
  DEFAULT_OLLAMA_BASE_URL,
  DEFAULT_OPENAI_COMPATIBLE_BASE_URL,
  DEFAULT_ZAI_BASE_URL,
  buildAlternateOpenAICompatibleUrl,
  buildProviderModelCreationPlan,
  buildProviderSdkInstancePlan,
  detectProviderFromModel,
  getKnownModelProviderPrefixes,
  isAnthropicOAuthToken,
  isCodexModel,
  isOfficialAnthropicBaseUrl,
  isOfficialOpenAIBaseUrl,
  isResponsesApiModel,
  normalizeAnthropicBaseUrl,
  normalizeDeepSeekBaseUrl,
  normalizeOllamaBaseUrl,
  normalizeOpenAICompatibleBaseUrl,
  shouldUseOpenAICompatibleChat,
  type ProviderFetchStrategy,
  type ProviderModelCreationPlan,
  type ProviderModelInvocationMethod,
  type ProviderModelInvocationPlan,
  type ProviderSdkAdapter,
  type ProviderSdkInstancePlan,
} from './providers/routing.js';

export {
  PROMPT_CACHE_THRESHOLDS,
  getCacheBreakpoints,
  getThinkingKwargsForModel,
  isAdaptiveModel,
  meetsCacheThreshold,
  normalizeToolId,
  sanitizeThinkingLevel,
  transformThinkingConfig,
  type CacheableContentType,
  type ThinkingConfig,
} from './providers/transforms.js';

// Config types - phase 3. Includes the reasoning-API shape that
// shared/constants/models.ts re-exports back out for renderer code.
export {
  type ReasoningType,
  type ReasoningConfig,
  type ModelShorthand,
  type ThinkingLevel,
  type EffortLevel,
  type Phase,
  type PhaseModelConfig,
  type PhaseThinkingConfig,
  MODEL_ID_MAP,
  MODEL_BETAS_MAP,
  THINKING_BUDGET_MAP,
  EFFORT_LEVEL_MAP,
  ADAPTIVE_THINKING_MODELS,
  DEFAULT_PHASE_MODELS,
  DEFAULT_PHASE_THINKING,
  MODEL_PROVIDER_MAP,
  resolveReasoningParams,
  buildThinkingProviderOptions,
} from './config/types.js';

export {
  AGENT_CONFIGS,
  ALL_BUILTIN_TOOLS,
  BASE_READ_TOOLS,
  BASE_WRITE_TOOLS,
  CONTEXT7_TOOLS,
  DIRECT_TASK_TOOLS,
  ELECTRON_TOOLS,
  GRAPHITI_MCP_TOOLS,
  LINEAR_TOOLS,
  MEMORY_MCP_TOOLS,
  PUPPETEER_TOOLS,
  SPEC_TOOLS,
  TOOL_GET_BUILD_PROGRESS,
  TOOL_GET_SESSION_CONTEXT,
  TOOL_RECORD_DISCOVERY,
  TOOL_RECORD_GOTCHA,
  TOOL_UPDATE_QA_STATUS,
  TOOL_UPDATE_SUBTASK_STATUS,
  WEB_TOOLS,
  getAgentConfig,
  getDefaultThinkingLevel,
  getRequiredMcpServers,
  getRequiredMcpServersFromConfig,
  mapMcpServerName,
  type AgentConfig,
  type AgentType,
  type McpConfig,
  type McpConfigResolveOptions,
  type McpServerResolveOptions,
  type ProjectCapabilities,
} from './config/agent-configs.js';

export {
  DEFAULT_EXECUTION_OPTIONS,
  ToolPermission,
  type ToolExecutionOptions,
  type ToolMetadata,
  type ToolPermission as ToolPermissionType,
  type ToolPolicyContext,
  type ToolUsageLimits,
  type ToolUsagePolicyContext,
  type ToolUsageState,
  type ToolWritePathPolicyContext,
} from './tools/types.js';

export {
  DEFAULT_MAX_DUPLICATE_READ_ONLY_CALLS,
  DEFAULT_READ_ONLY_TOOL_LIMITS,
  buildReadOnlyToolSignature,
  createToolUsageState,
  getToolUsageState,
  getToolWritePathDenial,
  guardReadOnlyToolUsage,
  normalizeToolSignatureValue,
  resolveToolUsageLimits,
  sanitizeFilePathArg,
  stableStringify,
} from './tools/policy.js';

export {
  buildEditPlan,
  countContentLines,
  countExactOccurrences,
  formatEditFileNotFound,
  formatWriteSuccess,
  getEditInputValidationError,
  normalizeFileMutationPathInput,
  validateJsonWriteContent,
  type EditPlanFailure,
  type EditPlanResult,
  type EditPlanSuccess,
} from './tools/file-mutations.js';

export {
  AGGRESSIVE_BASH_MAX_OUTPUT_LENGTH,
  AGGRESSIVE_BASH_MAX_STDERR_LENGTH,
  BASH_MAX_OUTPUT_LENGTH,
  DEFAULT_BASH_TIMEOUT_MS,
  MAX_BASH_TIMEOUT_MS,
  clampBashTimeout,
  detectFastCommandFailure,
  formatBackgroundCommandStarted,
  formatBashCommandDenied,
  formatBashExecutionResult,
  hasNonAscii,
  isCompilerCommand,
  truncateBashOutput,
  truncateCompilerOutput,
  type BashExecutionResult,
  type FastCommandFailureOptions,
} from './tools/bash.js';

export {
  AUTOCODE_TOOL_REGISTRATION_ORDER,
  LOCAL_TOOL_REGISTRATION_ORDER,
  SPAWN_SUBAGENT_TOOL_NAME,
  buildToolRegistrationPlan,
  getAllowedToolNamesForAgent,
  selectRegisteredToolNamesForAgent,
  shouldExposeRegisteredTool,
  type ToolRegistrationPlanOptions,
  type ToolSelectionOptions,
} from './tools/registry.js';

export {
  SAFETY_NET_MAX_BYTES,
  TOOL_OUTPUT_MAX_BYTES,
  TOOL_OUTPUT_MAX_LINES,
  buildToolOutputTruncationContent,
  planToolOutputTruncation,
  sanitizeToolOutputName,
  type ToolOutputTruncationContentOptions,
  type ToolOutputTruncationPlan,
} from './tools/truncation.js';

export {
  AGGRESSIVE_READ_LINE_LIMIT,
  BALANCED_READ_LINE_LIMIT,
  DEFAULT_READ_LINE_LIMIT,
  LARGE_TEXT_DEFAULT_LINE_LIMIT,
  LARGE_TEXT_FILE_BYTES,
  LEGACY_TEXT_ENCODINGS,
  MAX_READ_LINE_LENGTH,
  READ_IMAGE_EXTENSIONS,
  READ_PDF_EXTENSION,
  TASK_LOG_SUMMARY_BYTES,
  buildLargeReadFileNote,
  decodeTextBuffer,
  formatImageReadResult,
  formatPdfReadResult,
  formatReadContent,
  formatWithLineNumbers,
  getDefaultReadLineLimit,
  getEffectiveReadLineLimit,
  isActiveTaskLogFile,
  isImageFile,
  isPdfFile,
  isTaskLogFile,
  joinReadNotes,
  normalizeComparableReadPath,
  normalizeReadPathInput,
  summarizeTaskLog,
  type DecodedTextBuffer,
  type EffectiveReadLimit,
  type ReadWorkflowMode,
} from './tools/read.js';

export {
  GLOB_MAX_RESULTS,
  GLOB_SUMMARY_SAMPLE_SIZE,
  GLOB_SUMMARY_THRESHOLD,
  GREP_DEFAULT_OUTPUT_MODE,
  GREP_MAX_FALLBACK_FILE_BYTES,
  GREP_MAX_FALLBACK_FILES,
  GREP_MAX_OUTPUT_LENGTH,
  SEARCH_EXCLUDED_DIRS,
  buildRipgrepArgs,
  formatGrepFallbackResults,
  isProbablyBinaryBuffer,
  matchesSearchType,
  normalizeSearchPathSegments,
  shouldExcludeSearchPath,
  shouldSkipSearchDir,
  summarizePathsByDirectory,
  toPortableSearchPath,
  truncateSearchOutput,
  type GrepFallbackMatch,
  type GrepOutputMode,
  type GrepSearchInput,
} from './tools/search.js';

export {
  type WorkspaceSummary,
  summarizeWorkspace,
} from './workspace/summary.js';

export {
  AUTOCODE_BUILD_OUTPUT_DIR_NAMES,
  AUTOCODE_COMMON_IGNORED_DIR_NAMES,
  AUTOCODE_DEPENDENCY_DIR_NAMES,
  AUTOCODE_GENERATED_DIR_NAMES,
  AUTOCODE_PROMPT_IGNORED_DIR_NAMES,
  AUTOCODE_TASK_GIT_CHANGE_HIDDEN_DIR_NAMES,
  AUTOCODE_TOOL_GENERATED_DIR_NAMES,
  formatAutocodeIgnoredDirNamesForPrompt,
  isAutocodeGeneratedPath,
  isAutocodeProjectDataPath,
  normalizeAutocodeRelativePathSegments,
  shouldHideAutocodeTaskGitChangePath,
  shouldSkipAutocodeWorkspaceDir,
  shouldSkipAutocodeWorkspacePath,
} from './workspace/ignore-rules.js';

export {
  BUILTIN_TO_SUPPORTED_PROVIDER,
  NO_AUTH_PROVIDERS,
  PROVIDER_BASE_URL_ENV,
  PROVIDER_ENV_VARS,
  PROVIDER_SETTINGS_KEY,
  ZAI_CODING_API,
  ZAI_GENERAL_API,
  buildProviderAccountQueueConfig,
  parseProviderAccounts,
  parseStringArraySetting,
  resolveApiKeyProviderAccountAuth,
  resolveDefaultProviderAuth,
  resolveProviderBaseUrlFromEnvironment,
  resolveProviderEnvironmentAuth,
  resolveProviderSettingsAuth,
  resolveZaiBaseUrlForBilling,
  sortProviderAccountsByPriority,
  toSupportedProvider,
  type AuthEnvironmentAccessor,
  type AuthResolverContext,
  type AuthSettingsAccessor,
  type AuthSource,
  type BillingModel,
  type BuiltinProvider,
  type CredentialSettingsAdapter,
  type OAuthBrowserAdapter,
  type OAuthTokenAdapter,
  type OAuthTokenFileAdapter,
  type ProviderAccountAdapter,
  type ProviderAccountAuthType,
  type ProviderAccountLike,
  type QueueResolvedAuth,
  type ResolvedAuth,
} from './auth/index.js';

export type {
  GitAdapter,
  NotificationAdapter,
  AgentRuntimeAdapter,
  SecretsAdapter,
  TaskExecutionAdapter,
  TerminalAdapter,
  WorkspaceAdapter,
} from './platform/interfaces/index.js';

export {
  type AutocodeAgentLanguage,
  type AutocodeAgentMessage,
  type AutocodeAgentMessageRole,
  type BuildAutocodeAgentPromptInput,
  type BuildAutocodeRuntimeMessagesInput,
  type BuildAutocodeSpecPromptInput,
  buildAutocodeCompletionSummaryRequirement,
  buildAutocodeDefaultDirectTaskPrompt,
  buildAutocodeDefaultPlannerPrompt,
  buildAutocodeDefaultQAPrompt,
  buildAutocodeDefaultSpecPrompt,
  buildAutocodeDirectTaskExecutionMessages,
  buildAutocodeQAInitialMessages,
  buildAutocodeTaskExecutionMessages,
} from './runtime/agent-messages.js';

export {
  type AutocodeProviderModelEquivalent,
  type AutocodeRuntimePhase,
  type AutocodeTaskRuntimeMetadataConfig,
  type ResolveAutocodeCrossProviderModelRequestOptions,
  type ResolveAutocodeTaskPhaseModelInput,
  type ResolveAutocodeTaskPhaseProviderOptions,
  inferAutocodePinnedProviderFromModel,
  inferAutocodeProviderFromModelValue,
  loadAutocodeTaskRuntimeMetadataConfig,
  resolveAutocodeCrossProviderModelRequest,
  resolveAutocodeModelId,
  resolveAutocodeTaskEnableBatchExecution,
  resolveAutocodeTaskPhaseModelId,
  resolveAutocodeTaskPhaseProvider,
  resolveAutocodeTaskWorkflowMode,
} from './runtime/task-runtime-config.js';

export {
  AUTOCODE_AGGRESSIVE_WORKFLOW_PHASE_STEP_BUDGETS,
  AUTOCODE_DEFAULT_SESSION_MAX_STEPS,
  AUTOCODE_DEFAULT_WORKFLOW_PHASE_STEP_BUDGETS,
  AUTOCODE_DIRECT_WORKFLOW_PHASE_STEP_BUDGETS,
  type AutocodeCustomMcpServer,
  type AutocodeRuntimePhaseStepBudgets,
  type AutocodeSessionMcpOptions,
  type AutocodeSessionRuntimeOptions,
  type BuildAutocodeSessionRuntimeOptionsInput,
  buildAutocodeSessionRuntimeOptions,
  parseAutocodeBooleanEnv,
  parseAutocodeCustomMcpServers,
} from './runtime/session-runtime-options.js';

export {
  type AutocodeAgentRuntimeMode,
  type AutocodeAgentRuntimeMetadata,
  type AutocodeAgentRuntimeOptions,
  type AutocodeAgentRuntimePlan,
  type AutocodeAgentRuntimeProcessType,
  type AutocodeAgentRuntimeStarter,
  type AutocodeAgentRuntimeTaskInput,
  type AutocodeTaskStartEvent,
  type CreateAutocodeAgentRuntimePlanInput,
  type ResolveAutocodeTaskStartEventInput,
  createAutocodeAgentRuntimePlan,
  getAutocodeAgentRuntimeModeLabel,
  resolveAutocodeAgentRuntimeMode,
  resolveAutocodeTaskStartEvent,
  startAutocodeAgentRuntime,
} from './runtime/agent-runtime.js';

export {
  type CreateTaskDraftInput,
  type TaskDraft,
  type TaskDraftStoreOptions,
  type TaskDraftStatus,
  createTaskDraft,
  getTaskDraftsFilePath,
  listTaskDrafts,
} from './tasks/drafts.js';

export {
  AUTOCODE_LEGACY_PROJECT_DATA_DIR_NAME,
  AUTOCODE_PROJECT_DATA_DIR_NAME,
  AUTOCODE_SPECS_DIR_NAME,
  AUTOCODE_TASK_ARTIFACT_FILE_NAMES,
  AUTOCODE_TASK_ARTIFACTS,
  type AutocodeTaskArtifactFileName,
  type AutocodeTaskArtifactName,
  getAutocodeSpecsRelativeDir,
  isAutocodeTaskArtifactFileName,
  normalizeAutocodeProjectDataDirName,
} from './tasks/artifacts.js';

export {
  AUTOCODE_COMMON_BASE_BRANCHES,
  AUTOCODE_DEFAULT_BASE_BRANCH,
  AUTOCODE_GIT_BRANCH_REGEX,
  AUTOCODE_PROJECT_DEFAULT_BRANCH_MARKER,
  AUTOCODE_TASK_BRANCH_PREFIX,
  type AutocodeCommonBaseBranch,
  type AutocodeWorktreeBranchValidationReason,
  type AutocodeWorktreeBranchValidationResult,
  buildAutocodeTaskBranchName,
  isAutocodeCommonBaseBranch,
  isAutocodeGitBranchName,
  isAutocodeTaskBranchName,
  normalizeAutocodeBaseBranch,
  parseAutocodeOriginHeadBranch,
  resolveAutocodeBaseBranchCandidate,
  validateAutocodeWorktreeBranch,
} from './tasks/branch-protocol.js';

export {
  AUTOCODE_LEGACY_WORKTREE_DIR_NAME,
  AUTOCODE_PR_WORKTREES_DIR_NAME,
  AUTOCODE_TASK_WORKTREES_DIR_NAME,
  AUTOCODE_TERMINAL_METADATA_DIR_NAME,
  AUTOCODE_TERMINAL_WORKTREES_DIR_NAME,
  AUTOCODE_WORKTREES_DIR_NAME,
  getAutocodeLegacyTaskWorktreesRelativeDir,
  getAutocodeLegacyTerminalWorktreesRelativeDir,
  getAutocodeLegacyFlatTaskWorktreePath,
  getAutocodePrWorktreeDir,
  getAutocodePrWorktreesRelativeDir,
  getAutocodeTaskWorktreeCandidatePaths,
  getAutocodeTaskWorktreeDir,
  getAutocodeTaskWorktreePath,
  getAutocodeTaskWorktreeSpecDir,
  getAutocodeTaskWorktreesRelativeDir,
  getAutocodeTerminalMetadataDir,
  getAutocodeTerminalMetadataPath,
  getAutocodeTerminalMetadataRelativeDir,
  getAutocodeTerminalWorktreeCandidatePaths,
  getAutocodeTerminalWorktreeDir,
  getAutocodeTerminalWorktreePath,
  getAutocodeTerminalWorktreesRelativeDir,
  isAutocodePathWithinBase,
  isValidAutocodePathId,
} from './tasks/worktree-paths.js';

export {
  type AutocodePlanSubtask,
  type AutocodePlanStatus,
  type AutocodeTaskCreationArtifacts,
  type AutocodeTaskCreationContext,
  type AutocodeExecutionPhase,
  type AutocodeReviewReason,
  type AutocodeSubtaskStatus,
  type AutocodeTask,
  type AutocodeTaskCategory,
  type AutocodeTaskComplexity,
  type AutocodeTaskImpact,
  type AutocodeTaskMetadata,
  type AutocodeTaskPathsInput,
  type AutocodeTaskPriority,
  type AutocodeTaskRequirements,
  type AutocodeTaskStatus,
  type AutocodeTaskWorkflowMode,
  type CreateImportedAutocodeTaskInput,
  type CreateAutocodeTaskInput,
  type ListAutocodeTasksInput,
  type UpdateAutocodeTaskPlanStatusInput,
  buildAutocodeSpecId,
  buildAutocodeTaskRequirements,
  createAutocodeTask,
  createImportedAutocodeTask,
  getAutocodeSpecDir,
  getAutocodeSpecsDir,
  listAutocodeTasks,
  slugifySpecTitle,
  updateAutocodeTaskPlanStatus,
} from './tasks/spec-store.js';

export {
  type AutocodeTaskPlanSeed,
  type AutocodeTokenUsage,
  type MutableAutocodePlan,
  type MutableAutocodePlanPhase,
  type MutableAutocodePlanSubtask,
  applyAutocodePlanPhase,
  applyAutocodePlanStatus,
  applyAutocodePlanStatusAndReason,
  applyAutocodePlanTokenUsage,
  canSyncAutocodePlanPhases,
  countAutocodePlanSubtasks,
  createMinimalAutocodePlan,
  inferAutocodeExecutionProgress,
  inferAutocodeExecutionProgressFromXState,
  mapAutocodeExecutionPhaseToTaskStatus,
  mapAutocodeTaskStatusToPlanStatus,
  mergeAutocodeTokenUsage,
  resetAutocodeStuckSubtasksInPlan,
} from './tasks/plan-file.js';

export {
  AUTOCODE_JSON_ERROR_PREFIX,
  AUTOCODE_JSON_ERROR_TITLE_SUFFIX,
  AUTOCODE_TASK_STATUS_PRIORITY,
  type AutocodeProjectTask,
  type AutocodeProjectTaskExecutionProgress,
  type LoadAutocodeProjectTasksInput,
  dedupeAutocodeProjectTasks,
  determineAutocodeProjectTaskStatus,
  loadAutocodeProjectTasks,
  loadAutocodeTasksFromSpecsDir,
} from './tasks/project-task-loader.js';

export {
  repairAutocodeJson,
  safeParseAutocodeJson,
} from './tasks/json-repair.js';

export {
  AUTOCODE_CLI_COMMANDS,
  DEFAULT_AUTOCODE_CLI,
  SUPPORTED_AUTOCODE_CLIS,
  buildAutocodeCliCommand,
  getAutocodeCliCommandName,
  getAutocodeCliPermissionArgs,
  getAutocodeCliPermissionBypassFlag,
  isAutocodeCli,
  resolveAutocodeCli,
  resolveAutocodeCliInvocation,
  splitAutocodeCliCommandLine,
  type AutocodeCli,
} from './tasks/cli-catalog.js';

export {
  type AutocodeTaskRunPhase,
  type AutocodeTaskRunPlan,
  type CreateAutocodeTaskRunPlanInput,
  buildAutocodeTaskRunnerShellCommand,
  buildAutocodeTaskRunShellCommand,
  createAutocodeTaskRunPlan,
} from './tasks/cli-runner.js';

export {
  type AppendAutocodeTaskLogEntryInput,
  type AutocodeTaskLogEntry,
  type AutocodeTaskLogEntryType,
  type AutocodeTaskLogPhase,
  type AutocodeTaskLogPhaseStatus,
  type AutocodeTaskLogs,
  type AutocodeTaskLogsInput,
  type AutocodeTaskPhaseLog,
  type UpdateAutocodeTaskLogPhaseInput,
  appendAutocodeTaskLogEntry,
  createEmptyAutocodeTaskLogs,
  combineAutocodeTaskPhaseLogs,
  getAutocodeTaskLogsPath,
  getAutocodeTaskLogsPathFromSpecDir,
  mergeAutocodeTaskLogs,
  parseAutocodeTaskLogs,
  readAutocodeTaskLogs,
  readAutocodeTaskLogsFromSpecDir,
  salvageAutocodeTaskLogs,
  updateAutocodeTaskLogPhase,
} from './tasks/logs.js';

export {
  type AutocodeCommandOptionValue,
  type ParsedAutocodeCommandArgs,
  getAutocodeBooleanOption,
  getAutocodeStringOption,
  hasAutocodeJsonOption,
  parseAutocodeCommandArgs,
  setAutocodeCommandOption,
} from './frontend/command-line.js';

export {
  type AutocodeDisplayRow,
  type AutocodeTaskCardViewModel,
  type AutocodeTaskDisplayInput,
  type AutocodeTaskLogEntryViewModel,
  type AutocodeTaskLogsViewModel,
  type AutocodeWorkspaceDisplayInput,
  type AutocodeWorkspaceSummaryViewModel,
  type AutocodeWorkspaceTasksViewModel,
  type BuildAutocodeTaskCardViewModelOptions,
  buildAutocodeTaskCardViewModel,
  buildAutocodeTaskLogEntryViewModel,
  buildAutocodeTaskLogsViewModel,
  buildAutocodeWorkspaceSummaryViewModel,
  buildAutocodeWorkspaceTasksViewModel,
  collectLatestAutocodeLogEntries,
  formatAutocodeDate,
  formatAutocodeList,
  formatAutocodeRelativeTime,
  formatAutocodeServiceList,
  truncateAutocodeText,
} from './frontend/task-view-model.js';

export {
  type AutocodeTaskActionInput,
  type AutocodeWorkspaceState,
  type BuildAutocodeWorkspaceStateInput,
  type CreateAutocodeAgentRuntimeStartPlanInput,
  type CreateManualAutocodeTaskInput,
  type StartedAutocodeTaskRun,
  buildAutocodeWorkspaceState,
  buildManualAutocodeTaskMetadata,
  createAutocodeAgentRuntimeStartPlan,
  createManualAutocodeTask,
  createStartedAutocodeTaskRun,
  markAutocodeTaskDone,
  markAutocodeTaskStopped,
  requestAutocodeTaskChanges,
} from './tasks/workspace-state.js';

export {
  BACKEND_PHASES,
  EXECUTION_PHASES,
  PAUSE_PHASES,
  PHASE_MARKER_PREFIX,
  PHASE_ORDER_INDEX,
  PHASE_PROTOCOL_VERSION,
  TERMINAL_PHASES,
  getExpectedPreviousPhase,
  isAllowedPhaseRegression,
  isPausePhase,
  isTerminalPhase,
  isValidBackendPhase,
  isValidExecutionPhase,
  isValidPhaseTransition,
  wouldPhaseRegress,
  type BackendPhase,
  type CompletablePhase,
  type ExecutionPhase,
} from './tasks/phase-protocol.js';

export {
  calculateProgress,
  countSubtasksByStatus,
  determineOverallStatus,
  estimateRemainingTime,
  formatProgressString,
} from './tasks/progress.js';

export {
  isCompletedAutocodeTask,
  isCompletedTask,
} from './tasks/task-status.js';

export {
  TASK_STATE_NAMES,
  XSTATE_ACTIVE_STATES,
  XSTATE_SETTLED_STATES,
  XSTATE_TO_PHASE,
  mapStateToLegacy,
  type TaskStateName,
} from './tasks/task-state-utils.js';

export {
  ALL_PATTERNS,
  BLOCKED_COMMANDS,
  DATABASE_PATTERNS,
  GENERIC_PATTERNS,
  PRIVATE_KEY_PATTERNS,
  SERVICE_PATTERNS,
  VALIDATORS,
  assertPathContained,
  bashSecurityHook,
  containsWindowsPath,
  crossPlatformBasename,
  extractCommands,
  getCommandForValidation,
  getSafeToolInput,
  getSecurityProfile,
  getValidator,
  isCommandAllowed,
  isCommandBlocked,
  isFalsePositive,
  isPathContained,
  loadSecretsIgnore,
  maskSecret,
  resetProfileCache,
  scanContent,
  scanFiles,
  shouldSkipFile,
  splitCommandSegments,
  validateBashSubshell,
  validateChmodCommand,
  validateCommand,
  validateDropdbCommand,
  validateDropuserCommand,
  validateGitCommand,
  validateInitScript,
  validateKillCommand,
  validateKillallCommand,
  validateMongoshCommand,
  validateMysqlCommand,
  validateMysqladminCommand,
  validatePkillCommand,
  validatePsqlCommand,
  validateRedisCliCommand,
  validateRmCommand,
  validateShSubshell,
  validateShellCCommand,
  validateToolInput,
  validateZshSubshell,
  type DenylistValidationResult,
  type HookInputData,
  type PathContainmentResult,
  type SecretMatch,
  type SecurityProfile,
  type ToolValidationResult,
  type ValidationResult,
  type ValidatorFunction,
} from './security/index.js';

export {
  AICommentTriageSchema,
  AICommentTriagesOutputSchema,
  ComplexityAssessmentOutputSchema,
  ComplexityAssessmentSchema,
  ExtractedInsightsOutputSchema,
  ExtractedInsightsSchema,
  FindingValidationArraySchema,
  FindingValidationResultSchema,
  FindingValidationsOutputSchema,
  ImplementationPlanOutputSchema,
  ImplementationPlanSchema,
  MRReviewResultSchema,
  PlanPhaseSchema,
  PlanSubtaskSchema,
  QAIssueSchema,
  QASignoffOutputSchema,
  QASignoffSchema,
  RequirementsOutputSchema,
  ResearchOutputSchema,
  ResolutionVerificationOutputSchema,
  ResolutionVerificationSchema,
  ReviewFindingSchema,
  ReviewFindingsArraySchema,
  ReviewFindingsOutputSchema,
  ScanResultOutputSchema,
  ScanResultSchema,
  SpecialistOutputOutputSchema,
  SpecialistOutputSchema,
  SpecContextOutputSchema,
  StructuralIssueSchema,
  StructuralIssuesOutputSchema,
  SynthesisResultOutputSchema,
  SynthesisResultSchema,
  TaskSuggestionSchema,
  TriageResultOutputSchema,
  TriageResultSchema,
  VerificationItemSchema,
  getOutputSchemaForAgent,
  validateImplementationPlanLanguage,
  type AICommentTriagesOutput,
  type ComplexityAssessmentOutput,
  type ExtractedInsightsOutput,
  type FindingValidationItemOutput,
  type FindingValidationsOutput,
  type ImplementationPlanOutput,
  type PhaseOutput,
  type QAIssueOutput,
  type QASignoffOutput,
  type RequirementsOutput,
  type ResearchOutput,
  type ResolutionVerificationOutput,
  type ReviewFindingsOutput,
  type ScanResultOutput,
  type SpecialistOutputOutput,
  type SpecContextOutput,
  type StructuralIssuesOutput,
  type SubtaskOutput,
  type SupportedLanguage,
  type SynthesisResultOutput,
  type TriageResultOutput,
  type ValidatedAICommentTriage,
  type ValidatedComplexityAssessment,
  type ValidatedExtractedInsights,
  type ValidatedFindingValidation,
  type ValidatedFindingValidationArray,
  type ValidatedImplementationPlan,
  type ValidatedMRReviewResult,
  type ValidatedPlanPhase,
  type ValidatedPlanSubtask,
  type ValidatedQAIssue,
  type ValidatedQASignoff,
  type ValidatedResolutionVerification,
  type ValidatedReviewFinding,
  type ValidatedReviewFindingsArray,
  type ValidatedScanResult,
  type ValidatedSpecialistOutput,
  type ValidatedStructuralIssue,
  type ValidatedSynthesisResult,
  type ValidatedTaskSuggestion,
  type ValidatedTriageResult,
  type ValidatedVerificationItem,
  type VerificationItemOutput,
} from './schema/index.js';

export {
  BASE_COMMANDS,
  CLOUD_COMMANDS,
  CODE_QUALITY_COMMANDS,
  DATABASE_COMMANDS,
  FRAMEWORK_COMMANDS,
  FrameworkDetector,
  INFRASTRUCTURE_COMMANDS,
  LANGUAGE_COMMANDS,
  PACKAGE_MANAGER_COMMANDS,
  ProjectAnalyzer,
  StackDetector,
  VERSION_MANAGER_COMMANDS,
  analyzeProject,
  buildProjectIndex,
  buildSecurityProfile,
  createCustomScripts,
  createProjectSecurityProfile,
  createTechnologyStack,
  runProjectIndexer,
  type ConventionsInfo,
  type CustomScripts,
  type InfrastructureInfo,
  type ProjectIndex,
  type ProjectSecurityProfile,
  type ProjectSourceSummary,
  type SerializedSecurityProfile,
  type ServiceInfo,
  type TechnologyStack,
} from './project/index.js';

export {
  AUTOCODE_COMPETITOR_ANALYSIS_FILE_NAME,
  AUTOCODE_GENERATION_PROGRESS_FILE_NAME,
  AUTOCODE_DEEPSEEK_SMART_TERMINAL_DIR_NAME,
  AUTOCODE_GITHUB_DIR_NAME,
  AUTOCODE_GITHUB_TMP_COMMENT_BODY_FILE_NAME,
  AUTOCODE_GITLAB_DIR_NAME,
  AUTOCODE_IDEATION_CONTEXT_FILE_NAME,
  AUTOCODE_IDEATION_DIR_NAME,
  AUTOCODE_IDEATION_FILE_NAME,
  AUTOCODE_INSIGHTS_CURRENT_SESSION_FILE_NAME,
  AUTOCODE_INSIGHTS_DIR_NAME,
  AUTOCODE_INSIGHTS_LEGACY_SESSION_FILE_NAME,
  AUTOCODE_INSIGHTS_SESSIONS_DIR_NAME,
  AUTOCODE_MANUAL_COMPETITORS_FILE_NAME,
  AUTOCODE_PROJECT_LOCKS_DIR_NAME,
  AUTOCODE_PROJECT_PROMPT_PROFILE_FILE_NAME,
  AUTOCODE_PROJECT_PROMPTS_DIR_NAME,
  AUTOCODE_PROJECT_ENV_FILE_NAME,
  AUTOCODE_PROJECT_INDEX_FILE_NAME,
  AUTOCODE_ROADMAP_DIR_NAME,
  AUTOCODE_ROADMAP_DISCOVERY_FILE_NAME,
  AUTOCODE_ROADMAP_FILE_NAME,
  AUTOCODE_SMART_TERMINAL_DIR_NAME,
  AUTOCODE_SPEC_NUMBER_LOCK_FILE_NAME,
  AUTOCODE_TOOL_OUTPUT_DIR_NAME,
  AUTOCODE_YUNXIAO_DIR_NAME,
  getAutocodeCompetitorAnalysisPath,
  getAutocodeDeepSeekSmartTerminalDir,
  getAutocodeGithubDir,
  getAutocodeGithubTmpCommentBodyPath,
  getAutocodeGitlabDir,
  getAutocodeIdeationContextPath,
  getAutocodeIdeationDir,
  getAutocodeIdeationFilePath,
  getAutocodeIdeationRelativeDir,
  getAutocodeIdeationTypeIdeasPath,
  getAutocodeInsightsCurrentSessionPath,
  getAutocodeInsightsDir,
  getAutocodeInsightsLegacySessionPath,
  getAutocodeInsightsRelativeDir,
  getAutocodeInsightsSessionPath,
  getAutocodeInsightsSessionsDir,
  getAutocodeManualCompetitorsPath,
  getAutocodeProjectDataDir,
  getAutocodeProjectDataPath,
  getAutocodeProjectDataRelativeDir,
  getAutocodeProjectDataRelativePath,
  getAutocodeProjectEnvPath,
  getAutocodeProjectEnvRelativePath,
  getAutocodeProjectIndexPath,
  getAutocodeProjectIndexRelativePath,
  getAutocodeProjectLocksDir,
  getAutocodeProjectPromptProfilePath,
  getAutocodeProjectPromptProfileRelativePath,
  getAutocodeProjectPromptsDir,
  getAutocodeProjectPromptsRelativeDir,
  getAutocodeRoadmapDir,
  getAutocodeRoadmapDiscoveryPath,
  getAutocodeRoadmapFilePath,
  getAutocodeRoadmapProgressPath,
  getAutocodeRoadmapRelativeDir,
  getAutocodeSpecNumberLockPath,
  getAutocodeToolOutputDir,
  getAutocodeYunxiaoDir,
} from './project/data-paths.js';
